export const enum Version {
	Unsupported = 1,
	Unknown2,
	Unknown3,
	Unknown4,
	Unknown5,
	Unknown6,
	Unknown7,
	Unknown8,
	Unknown9,
	Unknown10,
	HasScriptTypeIndex,
	Unknown12,
	HasTypeTreeHashes,
	Unknown14,
	SupportsStrippedObject,
	RefactoredClassId,
	RefactorTypeData,
	RefactorShareableTypeTreeData,
	TypeTreeNodeWithTypeFlags,
	SupportsRefObject,
	StoresTypeDependencies,
	LargeFileSupport,
}
